create table if not exists box (
  player varchar(100),
  dnp numeric,
  dnpr varchar(100),
  vs varchar(100),
  game_id numeric,
  min numeric,
  fg varchar(100),
  threept varchar(100),
  ft varchar(100),
  oreb numeric,
  dreb numeric,
  reb numeric,
  ast numeric,
  stl numeric,
  blk numeric,
  tov numeric,
  pf numeric,
  pm numeric,
  pts numeric,
  team varchar(100),
  month numeric,
  day numeric,
  year numeric,
  time varchar(100),
  t_min numeric,
  t_fg varchar(100),
  t_threept varchar(100),
  t_ft varchar(100),
  t_oreb numeric,
  t_dreb numeric,
  t_reb numeric,
  t_ast numeric,
  t_stl numeric,
  t_blk numeric,
  t_tov numeric,
  t_pf numeric,
  t_pm numeric,
  t_pts numeric,
  fg_p numeric,
  threept_p numeric,
  ft_p numeric,
  team_ref varchar(100),
  threept_made varchar(100),
  threept_att varchar(100),
  fg_made varchar(100),
  fg_att varchar(100),
  ft_made varchar(100),
  ft_att varchar(100),
  t_threept_made varchar(100),
  t_threept_att varchar(100),
  t_fg_made varchar(100),
  t_fg_att varchar(100),
  t_ft_made varchar(100),
  t_ft_att varchar(100)
);


create table if not exists site (
  id bigserial primary key,
  game_id varchar(20) unique,
  html text
);
